steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/apytracker-backend', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apytracker-backend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'apytracker-backend'
    - '--image=gcr.io/$PROJECT_ID/apytracker-backend'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=512Mi'
    - '--min-instances=0'
    - '--max-instances=10'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/apytracker-backend'

# Set a timeout (optional)
timeout: '1200s'

# Configure logging and service account
options:
  logging: CLOUD_LOGGING_ONLY

# Specify the service account to use
serviceAccount: 'projects/apytracker-backend/serviceAccounts/svc-apytracker@apytracker-backend.iam.gserviceaccount.com'
